# Generated by Django 2.1.1 on 2018-11-14 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0002_member_this_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='this_member',
        ),
        migrations.AddField(
            model_name='member',
            name='this_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
